### ISSUE TITLE
gem fails to build under ruby-2.2.4

### ISSUE THREAD

**Issue by mattmartini** [theunraveler/taskwarrior-web#87]
Building the taskwarrior-web gem fails to build using ruby-2.2.4 via rvm.

```
$ gem install taskwarrior-web
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Fetching: parseconfig-1.0.8.gem (100%)
Successfully installed parseconfig-1.0.8
Fetching: vegas-0.1.11.gem (100%)
Successfully installed vegas-0.1.11
Fetching: rinku-2.0.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rinku-2.0.2
Fetching: blockenspiel-0.5.0.gem (100%)
Successfully installed blockenspiel-0.5.0
Fetching: versionomy-0.5.0.gem (100%)
Successfully installed versionomy-0.5.0
Fetching: activesupport-3.2.22.5.gem (100%)
Successfully installed activesupport-3.2.22.5
Fetching: simple-navigation-4.0.3.gem (100%)
Successfully installed simple-navigation-4.0.3
Fetching: sinatra-simple-navigation-4.0.0.gem (100%)
Successfully installed sinatra-simple-navigation-4.0.0
Fetching: rack-flash3-1.0.5.gem (100%)
Successfully installed rack-flash3-1.0.5
Fetching: json-1.7.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing taskwarrior-web:
	ERROR: Failed to build gem native extension.

    /Users/martini/.rvm/rubies/ruby-2.2.4/bin/ruby -r ./siteconf20161126-35011-16f7td5.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/martini/.rvm/rubies/ruby-2.2.4/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/martini/.rvm/gems/ruby-2.2.4@taskwarrior/gems/json-1.7.7 for inspection.
Results logged to /Users/martini/.rvm/gems/ruby-2.2.4@taskwarrior/extensions/x86_64-darwin-14/2.2.0-static/json-1.7.7/gem_make.out

```

**Comment by mattmartini** [comment]
I noticed that it was actually json 1.7.7 that fails to build.  Installing json (2.0.2) doesn't fail.  But the gem install of taskwarrior-web doesn't recognize json-2.0.2 and tries to build json-1.7.7 which fails.

```
$ gem install json
Fetching: json-2.0.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-2.0.2
1 gem installed

```

```
$ gem install taskwarrior-web
Building native extensions.  This could take a while...
ERROR:  Error installing taskwarrior-web:
	ERROR: Failed to build gem native extension.

    /Users/martini/.rvm/rubies/ruby-2.2.4/bin/ruby -r ./siteconf20161126-62257-8pqx8p.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/martini/.rvm/rubies/ruby-2.2.4/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/martini/.rvm/gems/ruby-2.2.4@taskwarrior/gems/json-1.7.7 for inspection.
Results logged to /Users/martini/.rvm/gems/ruby-2.2.4@taskwarrior/extensions/x86_64-darwin-14/2.2.0-static/json-1.7.7/gem_make.out
```

**Comment by derekslenk** [comment]
It works when building from source. The RubyGem needs to be updated

**Comment by theunraveler** [comment]
Pushed to rubygems, should be fixed.
