### ISSUE TITLE
gem fails to build under ruby-2.3.1

### ISSUE THREAD

**Issue by mattmartini** [theunraveler/taskwarrior-web#88]
Building the taskwarrior-web gem fails to build using ruby-2.3.1 via rvm.

```
$ gem install taskwarrior-web
Fetching: json-1.7.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing taskwarrior-web:
	ERROR: Failed to build gem native extension.

    current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
/Users/martini/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20161126-27513-pdap5l.rb extconf.rb
creating Makefile

current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/martini/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7 for inspection.
Results logged to /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/extensions/x86_64-darwin-14/2.3.0/json-1.7.7/gem_make.out

```

**Comment by mattmartini** [comment]
noticed that it was actually json 1.7.7 that fails to build. Installing json (2.0.2) doesn't fail. But the gem install of taskwarrior-web doesn't recognize json-2.0.2 and tries to build json-1.7.7 which fails.

```
$ gem install thin erubis json
Fetching: eventmachine-1.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.2.1
Fetching: daemons-1.2.4.gem (100%)
Successfully installed daemons-1.2.4
Fetching: thin-1.7.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed thin-1.7.0
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: json-2.0.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-2.0.2
5 gems installed
```

```
$ gem install taskwarrior-web
Fetching: json-1.7.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing taskwarrior-web:
	ERROR: Failed to build gem native extension.

    current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
/Users/martini/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20161126-86539-1gbx1iy.rb extconf.rb
creating Makefile

current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/martini/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/gems/json-1.7.7 for inspection.
Results logged to /Users/martini/.rvm/gems/ruby-2.3.1@taskwarrior/extensions/x86_64-darwin-14/2.3.0/json-1.7.7/gem_make.out

```

**Comment by andrey-str** [comment]
@mattmartini try to build from sources, the version at rubygems is outdated.

**Comment by derekslenk** [comment]
@andrey-str how do you build from source? I am not seeing instructions

**Comment by theunraveler** [comment]
Pushed to rubygems, should be fixed.
